# Site settings
title: Reading List - A free app for iPhone, iPad and iPod touch
tag_text: Reading List
description: Reading List, on iPhone, iPad and iPod touch, is an app to track and record personal reading lists.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  sass_dir: _sass
  style: compressed
